// App config: ~/.config/claude-pet/config.json (%APPDATA%\claude-pet on Windows)

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct Prices {
    pub opus_in: f64,
    pub opus_out: f64,
    pub sonnet_in: f64,
    pub sonnet_out: f64,
    pub haiku_in: f64,
    pub haiku_out: f64,
    /// Cache-write multiplier relative to the input price
    pub cache_write_mult: f64,
    /// Cache-read multiplier relative to the input price
    pub cache_read_mult: f64,
}

impl Default for Prices {
    fn default() -> Self {
        // Unit: USD per million tokens. Prices change; can be edited in config.json
        Prices {
            opus_in: 15.0,
            opus_out: 75.0,
            sonnet_in: 3.0,
            sonnet_out: 15.0,
            haiku_in: 0.8,
            haiku_out: 4.0,
            cache_write_mult: 1.25,
            cache_read_mult: 0.1,
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct Config {
    /// auto | subscription | api
    pub mode: String,
    /// Hook server listen port
    pub port: u16,
    /// Hook server listen address. Defaults to localhost only; WSL NAT mode needs "0.0.0.0"
    /// (note: 0.0.0.0 exposes it to the LAN, and the firewall will prompt once)
    pub bind: String,
    /// Subscription-mode 5-hour window token limit. 0 = auto (use the historical peak window)
    pub block_limit: u64,
    /// Whether to send system notifications
    pub notify: bool,
    /// Completion-notification denoising: don't notify for jobs shorter than this many seconds
    pub notify_min_secs: u64,
    /// Sound (completion "ding" / soft chime when waiting for input), off by default
    pub sound: bool,
    /// Skin: classic (default) / a filename under the skins/ directory
    pub skin: String,
    /// Boss key (global shortcut) accelerator string, e.g. "CommandOrControl+Shift+B".
    /// Summons/hides the pet in one press; same format as a Tauri accelerator (Cmd/Ctrl/Alt/Shift + key)
    pub boss_key: String,
    /// A release version the user chose to skip; automatic update checks won't re-prompt for it
    pub skip_version: String,
    /// Remembered window position (physical pixels), None = system default
    pub pos_x: Option<i32>,
    pub pos_y: Option<i32>,
    /// Windows only: the pet's on-screen anchor = its canvas-top Y (physical pixels). The collapsed
    /// window is pre-allocated to the full panel height, so the window's own top-left is
    /// layout-dependent (pet at window bottom in up-layout, top in below-layout) and can't be
    /// restored directly — this layout-independent anchor is what we persist and restore instead.
    /// Migrated once from the old `pos_y` (the old collapsed window top equaled the pet canvas top).
    pub pet_anchor_y: Option<i32>,
    /// Claude Code OAuth token (sk-ant-oat…, generated by `claude setup-token`),
    /// used by official usage mode. If empty, try to read it automatically from Claude Code's credential store
    pub oauth_token: String,
    /// Full-scope token saved by the panel's "connect Claude account" (auto-renewed)
    pub oauth_access: String,
    pub oauth_refresh: String,
    pub oauth_expires_ms: i64,
    pub prices: Prices,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            mode: "auto".into(),
            port: 8737,
            bind: "127.0.0.1".into(),
            block_limit: 0,
            notify: true,
            notify_min_secs: 30,
            sound: false,
            skin: "classic".into(),
            boss_key: "CommandOrControl+Shift+B".into(),
            skip_version: String::new(),
            pos_x: None,
            pos_y: None,
            pet_anchor_y: None,
            oauth_token: String::new(),
            oauth_access: String::new(),
            oauth_refresh: String::new(),
            oauth_expires_ms: 0,
            prices: Prices::default(),
        }
    }
}

impl Config {
    pub fn path() -> PathBuf {
        dirs::config_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("claude-pet")
            .join("config.json")
    }

    pub fn load() -> Config {
        let p = Self::path();
        if let Ok(text) = fs::read_to_string(&p) {
            if let Ok(cfg) = serde_json::from_str::<Config>(&text) {
                return cfg;
            }
        }
        let cfg = Config::default();
        let _ = cfg.save();
        cfg
    }

    pub fn save(&self) -> std::io::Result<()> {
        let p = Self::path();
        if let Some(dir) = p.parent() {
            fs::create_dir_all(dir)?;
        }
        fs::write(&p, serde_json::to_string_pretty(self).unwrap())
    }

    /// Resolve the actual billing mode: subscription or API.
    /// The auto decision is heuristic: ANTHROPIC_API_KEY present in the environment → API billing,
    /// otherwise treated as subscription (OAuth login). Switch manually in the panel if the guess is wrong.
    pub fn resolved_mode(&self) -> &'static str {
        match self.mode.as_str() {
            "subscription" => "subscription",
            "api" => "api",
            _ => {
                if std::env::var("ANTHROPIC_API_KEY").map(|v| !v.is_empty()).unwrap_or(false) {
                    "api"
                } else {
                    "subscription"
                }
            }
        }
    }
}
